config/routes.rb
Rails.application.routes.draw do
  # Routes pour l'authentification des utilisateurs avec Devise
  devise_for :users

  # Routes pour les utilisateurs, avec des actions show, edit, update et custom pour le profil
  resources :users, only: [:show, :edit, :update] do 
    member do
      get :edit_profile
      patch :update_profile
    end
  end

  # Routes pour les événements
  resources :events

  # Routes pour les participations (attendances)
  resources :attendances, only: [:index]

  # Routes authentifiées pour l'utilisateur connecté (profil)
  authenticate :user do 
    resources :users, only: [:show]
  end

  # Route stripe
  scope '/checkout' do
    post 'create', to: 'checkouts#create', as: 'checkout_create'
    get 'success', to: 'checkouts#success', as: 'checkout_success'
    get 'cancel', to: 'checkouts#cancel', as: 'checkout_cancel'
  end

  resources :events
  

  # Route d'accueil
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendances
    has_many :attendees, through: :attendances, source: :user 
    belongs_to :creator, class_name: 'User'

    validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :events, foreign_key: 'creator_id', class_name: 'Event'
    has_many :attendances
    has_many :attended_events, through: :attendances, source: :event 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user! # Assurez-vous que l'utilisateur est connecté
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
    before_action :authenticate_user!
  
    def create
      @user = current_user
      @total = params[:total].to_d
      @event_id = params[:event_id]
  
      # Créer une session Stripe
      @session = Stripe::Checkout::Session.create(
        payment_method_types: ["card"],
        line_items: [
          {
            price_data: {
              currency: "eur",
              unit_amount: (@total * 100).to_i,  # Conversion en centimes
              product_data: {
                name: "Rails Stripe Checkout"
              }
            },
            quantity: 1
          }
        ],
        mode: "payment",
        success_url: checkout_success_url + "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url: checkout_cancel_url + "?session_id={CHECKOUT_SESSION_ID}",
        metadata: {
          event_id: @event_id  # Met l'ID de l'événement dans les métadonnées
        }
      )
  
      # Rediriger l'utilisateur vers Stripe Checkout
      redirect_to @session.url, allow_other_host: true
    end
  
    def success
      # Récupérer la session Stripe après le succès du paiement
      @session = Stripe::Checkout::Session.retrieve(params[:session_id])
      @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
      @event_id = @session.metadata.event_id
  
      # Trouver l'ordre en fonction de l'ID de l'événement
      order = Order.find_by(event_id: @event_id)
  
      if order && order.status == "pending"
        order.update(status: "validated")  # Valider la commande
        # Vous pouvez ajouter des actions supplémentaires ici si nécessaire
      end
    end
  
    def cancel
      # Annuler l'ordre en fonction de l'ID de l'événement
      @order = current_user.orders.find_by(event_id: @event_id)
      if @order && @order.status == "pending"
        @order.update(status: "cancelled")
        @order.destroy  # Supprimer l'ordre
      end
      redirect_to checkout_cancel_url, allow_other_host: true
    end
  end
  

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :destroy]

  def index
    @events = Event.all
  end

  def show
    # Affichage de l'événement
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.creator = current_user # Associe l'utilisateur comme créateur de l'événement
    if @event.save
      redirect_to event_path(@event), notice: "Ton événement est bien enregistré."
    else
      render :new
    end
  end

  def destroy
    # Vérifie si l'utilisateur actuel est le créateur de l'événement
    if @event.creator == current_user
      @event.destroy
      redirect_to events_path, notice: "Événement supprimé avec succès."
    else
      redirect_to events_path, alert: "Vous ne pouvez pas supprimer cet événement."
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :location, :date, :price)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!  # S'assure que l'utilisateur est connecté avant d'accéder à la méthode show
  before_action :correct_user, only: [:show, :edit, :update]  # Limite l'accès à la page profil à l'utilisateur connecté

  def show
    @user = current_user  # Récupère l'utilisateur connecté
    @events = @user.events  # Récupère tous les événements créés par cet utilisateur
  end
  

  def edit
    @user = current_user  # Récupère l'utilisateur connecté pour l'édition de son profil
    # Si l'utilisateur n'est pas le bon, redirige vers la page d'accueil
    redirect_to(root_url) unless current_user == @user
  end

  def update
    @user = current_user  # Récupère l'utilisateur connecté pour mettre à jour son profil
    if @user.update(user_params)
      redirect_to @user, notice: 'Profil mis à jour avec succès.'
    else
      render :edit  # En cas d'erreur de validation, redirige vers le formulaire d'édition
    end
  end

  private

  def user_params
    if params[:user][:password].present?
      params.require(:user).permit(:first_name, :last_name, :description, :email, :password, :password_confirmation, :current_password)
    else
      params.require(:user).permit(:first_name, :last_name, :description, :email)
    end
  end
  
  

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user == @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checkouts/cancel.html.erb
<h1>Paiement annulé</h1>
<p>Votre paiement a été annulé. Veuillez réessayer.</p>
<p><%= link_to 'Retour à l\'événement', event_path(@event) %></p>

app/views/checkouts/create.js.erb
var stripe = Stripe('<%= Rails.application.credentials.stripe[:public_key] %>');
stripe.redirectToCheckout({ sessionId: '<%= @session.id %>' })
  .then(function (result) {
    if (result.error) {
      alert(result.error.message);  // Affiche l'erreur si quelque chose ne va pas
    }
  });

app/views/checkouts/success.html.erb
<h1>Paiement réussi</h1>
<p>Merci pour votre achat ! Vous avez payé <%= @amount_paid %> € pour l'événement <%= @event.name %>.</p>
<p><%= link_to 'Retour à l\'événement', event_path(@event) %></p>

app/views/events/index.html.erb
<h1 class="text-center my-5">Événements</h1>

<div class="container">
  <% @events.each do |event| %>
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title"><%= event.title %></h5>
        <p class="card-text"><%= event.description.truncate(100) %></p>
        <p class="text-muted">
          <% if event.date.present? %>
            <%= event.date.strftime("%d/%m/%Y %H:%M") %>
          <% else %>
            Date non définie
          <% end %>
        </p>
      </div>
      <div class="card-footer text-center border-0 bg-transparent">
        <%= link_to 'Voir l\'événement', event_path(event), class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<h1 class="text-center my-5">Créer un événement</h1>

<%= form_with model: @event, local: true, class: "form-container" do |form| %>
  <% if @event.errors.any? %>
    <div class="flash-error mb-4">
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, "Titre", class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, "Description", class: "form-label" %>
    <%= form.text_area :description, class: "form-control", rows: 4 %>
  </div>

  <div class="mb-3">
    <%= form.label :date, "Date et Heure", class: "form-label" %>
    <%= form.text_field :date, class: "form-control", type: "datetime-local" %>
  </div>

  <div class="mb-3">
    <%= form.label :location, "Lieu", class: "form-label" %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :price, "Prix", class: "form-label" %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="d-flex justify-content-between">
    <div>
      <%= form.submit "Créer l'événement", class: "btn btn-success" %>
    </div>
    <div>
      <%= link_to 'Retour', events_path, class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<p><strong>Description:</strong> <%= @event.description %></p>
<p><strong>Lieu:</strong> <%= @event.location %></p>

<% if @event.date.present? %>
  <p><strong>Date de début:</strong> <%= @event.date.strftime("%d/%m/%Y %H:%M") %></p>
<% else %>
  <p><strong>Date de début:</strong> Non définie</p>
<% end %>

<% if @event.price.present? %>
  <p><strong>Prix:</strong> <%= @event.price %> €</p>
<% else %>
  <p><strong>Prix:</strong> Non spécifié</p>
<% end %>

<p><strong>Créateur:</strong> <%= @event.creator.email %></p>

<% if @event.attendees.any? %>
  <p><strong>Nombre d'inscrits:</strong> <%= @event.attendees.count %></p>
<% else %>
  <p><strong>Nombre d'inscrits:</strong> Aucun inscrit pour cet événement.</p>
<% end %>

<% if @event.creator == current_user %>
  <!-- Affichage du bouton supprimer uniquement si l'utilisateur est le créateur -->
  <%= link_to 'Supprimer cet événement', event_path(@event), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cet événement ?" }, class: "btn btn-danger" %>
<% end %>

<%= button_to 'Payer avec Stripe', checkout_create_path(event_id: @event.id, total: @event.price), method: :post, class: 'btn btn-success',  data: { turbo: false } %>


<%= link_to 'Retour à la liste des événements', events_path, class: 'btn btn-secondary' %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bienvenue sur Eventbrite THP</title>
  <!-- Lien vers le fichier CSS externe -->
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<nav class="navbar">
<div class="navbar-container">
  <a href="/" class="logo">Eventbrite THP</a>
  <ul class="nav-links">
    <li><a href="/">Accueil</a></li>
    <li><a href="/events">Événements</a></li>
    <li><a href="/about">À propos</a></li>
    <li><a href="/contact">Contact</a></li>
  </ul>

  <!-- Recherche combinée -->
  <div class="search-container">
    <input type="text" class="search-bar" id="event-search" placeholder="Rechercher un événement...">
    <input type="text" class="search-bar" id="city-search" placeholder="Dans quelle ville ?" />
  </div>

  <div class="hamburger" id="hamburger">
    <span class="bar"></span>
    <span class="bar"></span>
    <span class="bar"></span>
  </div>
</div>
</nav>

  <h1>Bienvenue sur Eventbrite by THP 🎉</h1>
  <p>Organise ou découvre des événements autour de toi. Connecte-toi, explore, participe et fais de belles rencontres !</p>

  <footer>
    Made with ❤️ by Nicolas - The Hacking Project
  </footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <title><%= content_for(:title) || "Eventbrite" %></title>
  <%= javascript_include_tag "application", "data-turbo-track": "reload" %>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  <!-- CDN Bootstrap -->
  <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js", crossorigin: "anonymous" %>

  <%= yield :head %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

   <!-- SCRIPT_STRIPE -->
  <script src="https://js.stripe.com/v3/"></script>
</head>

<body>
<!-- Navbar Bootstrap -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Eventbrite</a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!-- Accueil bouton avec un style uniforme -->
        <li class="nav-item">
          <a class="btn btn-light nav-link active" href="<%= root_path %>">Accueil</a>
        </li>
        
        <!-- Boutons pour création d'événements ou connexion selon l'état de l'utilisateur -->
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to 'Créer un événement', new_event_path, class: 'btn btn-primary' %>
          <% else %>
            <%= link_to 'Se connecter', new_user_session_path, class: 'btn btn-secondary' %>
          <% end %>
        </li>
        
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Mon profil', user_path(current_user), class: "btn btn-info" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'S\'inscrire', new_user_registration_path, class: "btn btn-success" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Se connecter', new_user_session_path, class: "btn btn-secondary" %>
        </li>
        <% end %>
      </ul>

      <!-- Zone de recherche -->
      <form class="d-flex" role="search" style="gap: 10px;">
        <input class="form-control me-2" type="search" placeholder="Rechercher un événement" aria-label="Search Events">
        <input class="form-control me-2" type="search" placeholder="Rechercher une ville" aria-label="Search City">
        <button class="btn btn-outline-light" type="submit">Rechercher</button>
      </form>
    </div>
  </div>
</nav>


  <!-- Le contenu de la page -->
  <div class="container" style="margin-top: 80px;">
    <%= yield %>
  </div>

  <!-- Script Bootstrap (pour les actions de la navbar) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  
</body>

</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h1>Modifier mes informations</h1>

<%= form_for(@user, url: user_path(@user)) do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :first_name, "Prénom" %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name, "Nom" %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Mettre à jour", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'Retour', user_path(@user), class: 'btn btn-secondary' %>

app/views/users/edit_profile.html.erb
<h1>Modifier mon profil</h1>

<%= form_for(@user, url: update_profile_user_path(@user)) do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Mettre à jour", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Profil de <%= @user.first_name %> <%= @user.last_name %></h1>

<p><strong>Email :</strong> <%= @user.email %></p>
<p><strong>Description :</strong> <%= @user.description || "Pas de description" %></p>

<h2>Mes événements :</h2>
<ul>
  <% @events.each do |event| %>
    <li><%= link_to event.title, event_path(event) %></li>
  <% end %>
</ul>

<%= link_to 'Modifier mon email et mon mot de passe', edit_user_registration_path, class: 'btn btn-secondary' %>


<%= link_to 'Éditer mon profil', edit_user_path(@user), class: 'btn btn-primary' %>